#!/usr/bin/env bash
# PreToolUse hook: block commits and PRs containing AI attribution.
# Checks only the commit message (after -m flag), not file paths or command args.

set -euo pipefail

INPUT=$(cat)

COMMAND=$(echo "$INPUT" | grep -o '"command":"[^"]*"' | head -1 | sed 's/"command":"//;s/"$//' || true)

if [ -z "$COMMAND" ]; then
  exit 0
fi

# Only check git commit and gh pr create commands
IS_GIT_COMMIT=$(echo "$COMMAND" | grep -ci 'git commit' || true)
IS_GH_PR=$(echo "$COMMAND" | grep -ci 'gh pr create' || true)

if [ "$IS_GIT_COMMIT" -eq 0 ] && [ "$IS_GH_PR" -eq 0 ]; then
  exit 0
fi

# Extract the message portion only (after -m or --message flag, or --body flag for PRs)
MESSAGE=$(echo "$COMMAND" | sed -n 's/.*-m ["\x27]\(.*\)["\x27].*/\1/p' || true)
if [ -z "$MESSAGE" ]; then
  MESSAGE=$(echo "$COMMAND" | sed -n 's/.*--body ["\x27]\(.*\)["\x27].*/\1/p' || true)
fi
if [ -z "$MESSAGE" ]; then
  MESSAGE=$(echo "$COMMAND" | sed -n 's/.*--title ["\x27]\(.*\)["\x27].*/\1/p' || true)
fi

# If we couldn't extract a message, check the full command but exclude .claude/ paths
if [ -z "$MESSAGE" ]; then
  MESSAGE=$(echo "$COMMAND" | sed 's|\.claude/[^ ]*||g')
fi

# Block AI attribution patterns in the message
HAS_COAUTHORED=$(echo "$MESSAGE" | grep -ci 'Co-Authored-By' || true)
HAS_CLAUDE=$(echo "$MESSAGE" | grep -ci '\bclaude\b' || true)
HAS_AI_ASSISTANT=$(echo "$MESSAGE" | grep -ci 'ai assistant\|ai-generated\|generated by ai\|generated with' || true)
HAS_ANTHROPIC=$(echo "$MESSAGE" | grep -ci 'anthropic\|noreply@anthropic' || true)

if [ "$HAS_COAUTHORED" -gt 0 ] || [ "$HAS_CLAUDE" -gt 0 ] || [ "$HAS_AI_ASSISTANT" -gt 0 ] || [ "$HAS_ANTHROPIC" -gt 0 ]; then
  echo "BLOCKED: Commit/PR message contains AI attribution (Co-Authored-By, Claude, Anthropic, etc.)." >&2
  echo "Remove all AI references from the message before committing." >&2
  exit 2
fi

exit 0
